//! What macOS's packet filter has to say for 80 and 443 to reach an unprivileged front end, as text.
//!
//! **Compiled on all three systems** so it is tested on all three; what writes any of it is
//! `macos/port_access.rs`. Three artifacts, and the third is the interesting one — see the T42
//! design, D3, and ADR 0012: pf is disabled on every boot and `pfctl -e` needs root, so a redirect
//! that is only installed is a redirect that works until the first reboot and then silently stops.

#![allow(
    dead_code,
    reason = "every renderer here is compiled on all three systems and called on one, which is the \
              module's whole purpose: on Windows and Linux they are read by the tests below and by \
              nothing else"
)]

use std::fmt::Write as _;

use mixengine_proto::privileged::PortRedirect;

use crate::Result;
use crate::markers::{Block, Insertion};

/// The anchor's name, as pf spells one.
pub(crate) const ANCHOR: &str = "mixengine";

/// Where its rules live. Beside Apple's own, in the directory pf.conf loads anchors from.
pub(crate) const ANCHOR_FILE: &str = "/etc/pf.anchors/mixengine";

/// The main ruleset, which declares the anchor and loads it.
pub(crate) const CONF_FILE: &str = "/etc/pf.conf";

/// The boot job that enables pf. See ADR 0012.
pub(crate) const PLIST_FILE: &str = "/Library/LaunchDaemons/dev.mixengine.pf.plist";

/// Its label, which is also its file name without the extension, as launchd expects.
pub(crate) const LABEL: &str = "dev.mixengine.pf";

/// Apple's own translation anchor, and the line ours goes after.
///
/// `/etc/pf.conf` is order-sensitive: every `rdr` rule must precede every filter rule, so a block
/// appended at the end of Apple's file is a file `pfctl` refuses to load.
pub(crate) const AFTER: &str = "rdr-anchor \"com.apple/*\"";

/// The managed block in the main ruleset.
const CONF: Block = Block::in_file(CONF_FILE);

/// The anchor file: one `rdr` per redirect, IPv4 only — D6.
///
/// Rendered from the numbers the helper has already validated. **The helper never accepts text** —
/// D5 — which is what keeps a compromised daemon from writing a rule of its own choosing into a file
/// root owns.
pub(crate) fn anchor(redirects: &[PortRedirect]) -> String {
    let mut text = String::from(
        "# Generated by MixEngine. Rewritten from the daemon's state; edits here are lost.\n",
    );

    for redirect in redirects {
        // The rule measured on a real runner, verbatim — see the T42 design, "What was measured".
        let _ = writeln!(
            text,
            "rdr pass on lo0 inet proto tcp from any to 127.0.0.1 port {} -> 127.0.0.1 port {}",
            redirect.answer, redirect.bind
        );
    }

    text
}

/// The two lines that go between the markers in `/etc/pf.conf`.
fn declaration(newline: &str) -> String {
    format!(
        "rdr-anchor \"{ANCHOR}\"{newline}load anchor \"{ANCHOR}\" from \"{ANCHOR_FILE}\"{newline}"
    )
}

/// `text` with our block in it, spliced immediately after Apple's own translation anchor.
///
/// # Errors
///
/// [`Error::MalformedBlock`](crate::Error::MalformedBlock) for a block somebody has half-edited.
pub(crate) fn declared(text: &str) -> Result<String> {
    let body = declaration(crate::markers::newline(text));

    CONF.splice(text, &body, Insertion::After(AFTER))
}

/// `text` with our block taken out, markers and all.
///
/// # Errors
///
/// [`Error::MalformedBlock`](crate::Error::MalformedBlock) for a block somebody has half-edited.
pub(crate) fn undeclared(text: &str) -> Result<String> {
    CONF.splice(text, "", Insertion::End)
}

/// Is our block already there, saying exactly this?
///
/// The probe's whole question on this system: `/dev/pf` belongs to root, so the daemon cannot ask pf
/// what it has loaded, and what it can do instead is compare three world-readable files against what
/// the grant would write — D9.
///
/// # Errors
///
/// [`Error::MalformedBlock`](crate::Error::MalformedBlock) for a block somebody has half-edited.
pub(crate) fn is_declared(text: &str) -> Result<bool> {
    let wanted = declaration(crate::markers::newline(text));

    Ok(CONF.body(text)?.is_some_and(|body| body == wanted))
}

/// The boot job: `pfctl -e -f /etc/pf.conf`, once, as root, and it exits.
///
/// **`KeepAlive` is `false` and it is written rather than left out**, because that is the whole of
/// ADR 0012's claim: this is a standing permission to run one fixed command at boot, not a process
/// that persists. A reader auditing the file should find the word rather than infer it from its
/// absence.
pub(crate) fn plist() -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \
         \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n\
         <plist version=\"1.0\">\n\
         <dict>\n\
         \t<key>Label</key>\n\
         \t<string>{LABEL}</string>\n\
         \t<key>ProgramArguments</key>\n\
         \t<array>\n\
         \t\t<string>/sbin/pfctl</string>\n\
         \t\t<string>-e</string>\n\
         \t\t<string>-f</string>\n\
         \t\t<string>{CONF_FILE}</string>\n\
         \t</array>\n\
         \t<key>RunAtLoad</key>\n\
         \t<true/>\n\
         \t<key>KeepAlive</key>\n\
         \t<false/>\n\
         </dict>\n\
         </plist>\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The file Apple ships, which is what this splices into. Its own words are the reason ADR 0012
    /// exists: *each component which utilizes PF is responsible for enabling and disabling*.
    const APPLE: &str = "\
#
# Default PF configuration file.
#
# This file contains the main ruleset, which gets automatically loaded
# at startup.  PF will not be automatically enabled, however.  Instead,
# each component which utilizes PF is responsible for enabling and disabling
# PF via -E and -X as documented in pfctl(8).
#
# See pf.conf(5) for syntax.
#

#
# com.apple anchor point
#
scrub-anchor \"com.apple/*\"
nat-anchor \"com.apple/*\"
rdr-anchor \"com.apple/*\"
dummynet-anchor \"com.apple/*\"
anchor \"com.apple/*\"
load anchor \"com.apple\" from \"/etc/pf.anchors/com.apple\"
";

    fn eighty() -> Vec<PortRedirect> {
        vec![
            PortRedirect {
                answer: 80,
                bind: 8080,
            },
            PortRedirect {
                answer: 443,
                bind: 8443,
            },
        ]
    }

    /// The rule that was measured on a real runner, verbatim. Written as a literal rather than
    /// assembled from parts, because what makes it trustworthy is that it is the same string that
    /// was seen to work — see the T42 design, "What was measured".
    #[test]
    fn the_anchor_is_the_rule_that_was_measured() {
        let text = anchor(&eighty());

        assert!(
            text.contains(
                "rdr pass on lo0 inet proto tcp from any to 127.0.0.1 port 80 -> 127.0.0.1 port 8080"
            ),
            "{text}"
        );
        assert!(
            text.contains(
                "rdr pass on lo0 inet proto tcp from any to 127.0.0.1 port 443 -> 127.0.0.1 port 8443"
            ),
            "{text}"
        );
    }

    /// D6. `::1` was measured *not* to be redirected by an `inet` rule, and a managed domain
    /// resolves to `127.0.0.1` and nothing else. A rule nobody needs is a rule nobody tests.
    #[test]
    fn the_anchor_names_one_address_family_and_it_is_ipv4() {
        let text = anchor(&eighty());

        assert!(!text.contains("inet6"), "{text}");
        assert!(!text.contains("::1"), "{text}");
    }

    /// D3's ordering constraint, which is the only reason `Insertion::After` exists: pf.conf takes
    /// every translation rule before every filter rule, and Apple's file has one of each.
    #[test]
    fn the_block_lands_between_apples_translation_anchor_and_its_filter_anchor() {
        let written = declared(APPLE).unwrap();

        let translation = written.find("rdr-anchor \"com.apple/*\"").unwrap();
        let ours = written.find("# BEGIN MixEngine").unwrap();
        let filter = written.find("\nanchor \"com.apple/*\"").unwrap();

        assert!(translation < ours, "{written}");
        assert!(ours < filter, "{written}");
    }

    /// T41's own criterion, applied to the second file this product edits: in, out, byte-identical.
    #[test]
    fn every_unrelated_line_of_apples_file_survives() {
        let written = declared(APPLE).unwrap();

        assert!(written.contains("load anchor \"com.apple\""), "{written}");
        assert_eq!(undeclared(&written).unwrap(), APPLE);
    }

    /// Writing twice writes the same file, which is what makes the helper's `AlreadyDone` a
    /// comparison rather than a judgement.
    #[test]
    fn declaring_a_file_that_already_declares_it_changes_nothing() {
        let once = declared(APPLE).unwrap();

        assert_eq!(declared(&once).unwrap(), once);
    }

    /// The probe's whole question on macOS, since `/dev/pf` belongs to root and cannot be asked.
    #[test]
    fn a_block_that_says_exactly_this_is_recognised_and_one_that_does_not_is_not() {
        assert!(!is_declared(APPLE).unwrap());
        assert!(is_declared(&declared(APPLE).unwrap()).unwrap());

        let stale = APPLE.replace(
            "rdr-anchor \"com.apple/*\"\n",
            "rdr-anchor \"com.apple/*\"\n# BEGIN MixEngine\nrdr-anchor \"old\"\n# END MixEngine\n",
        );

        assert!(
            !is_declared(&stale).unwrap(),
            "a different block is not ours"
        );
    }

    /// ADR 0012's whole subject, and the reason a person reading this file should be able to see
    /// exactly what root will be allowed to run at boot.
    #[test]
    fn the_boot_job_runs_one_fixed_command_and_does_not_stay_up() {
        let text = plist();

        assert!(text.contains("<string>dev.mixengine.pf</string>"), "{text}");
        assert!(text.contains("<string>/sbin/pfctl</string>"), "{text}");
        assert!(text.contains("<key>RunAtLoad</key>"), "{text}");
        assert!(text.contains("<key>KeepAlive</key>\n\t<false/>"), "{text}");
    }
}
