// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageChannel } from "./PackageChannel";
import type { PackageVersion } from "./PackageVersion";

/**
 * One version the index offers, and whether this machine already has it.
 */
export type PackageRelease = { 
/**
 * Which package.
 */
package: string, 
/**
 * Which version.
 */
version: PackageVersion, 
/**
 * Which channel it is published on. Only [`PackageChannel::Stable`] is offered without a
 * setting.
 */
channel: PackageChannel, 
/**
 * Upstream's end of security support, when upstream states one.
 */
eol?: string | null, 
/**
 * How large the download is, so a client can say so before somebody commits to it.
 */
bytes: number, 
/**
 * Whether this exact version is already on this machine.
 */
installed: boolean, };
