// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageChannel } from "./PackageChannel";
import type { PackageVersion } from "./PackageVersion";
import type { RuntimeKind } from "./RuntimeKind";

/**
 * One version the index offers, and whether this machine already has it.
 *
 * Deliberately *not* [`RuntimeSummary`] with empty fields. What is knowable about something
 * installed and about something merely offered is different — there is no path and no install
 * moment for the second, and no download size worth showing for the first — and one type carrying
 * both would be a type where half the fields are meaningless in half the answers.
 */
export type RuntimeRelease = { 
/**
 * Which language.
 */
kind: RuntimeKind, 
/**
 * Which version.
 */
version: PackageVersion, 
/**
 * Which channel it is published on. Only [`PackageChannel::Stable`] is offered without a
 * setting.
 */
channel: PackageChannel, 
/**
 * Upstream's end of security support, when upstream states one.
 *
 * A version past it stays installable and is marked: the people who reach for a local
 * development environment are very often the people maintaining something old.
 */
eol?: string | null, 
/**
 * How large the download is, so a client can say so before somebody commits to it.
 */
bytes: number, 
/**
 * Whether this exact version is already on this machine.
 *
 * Composed by the daemon out of the index and the `runtime_installs` rows, rather than left to
 * the client to work out by cross-referencing two lists — which is business logic, and a place
 * for two clients to disagree about what "installed" means.
 */
installed: boolean, };
